In [1]:
#Broadcasting functions
import numpy as np

In [2]:
#Basic array operations
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [4]:
#Broadcasting allows to perform operatons between different sizes of arrays
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
#a array is being streched into 3 rows so that it can compute with M array which is 3x3 
#matrix
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [9]:
a = np.arange(3)
b = np.array([[0],
       [1],
       [2]])
print("array a:",a)
print("array b:", b)
b+a

#In the above example both of the array is in uncommon shape so 
#both of the array is stretched into a common shape

array a: [0 1 2]
array b: [[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
#Rules of Broadcasting

    # Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    # Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    # Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.


In [10]:
# Rule 1: If the arrays do not have the same rank, pad the smaller shape with ones on its left side.

a = np.array([1, 2, 3])  # Shape: (3,) -> Shape : (1,3)
b = np.array([[4], [5], [6]])  # Shape: (3, 1)

# Broadcasting a 1D array to a 2D array
result = a + b

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [11]:
# Rule 2: Compare the sizes of each dimension. If they are not equal, one of them must be 1.
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
b = np.array([10, 20, 30])  # Shape: (3,) -> Shapre: (2, 3)

# Broadcasting a 2D array to a 1D array
result = a + b

print(result)

[[11 22 33]
 [14 25 36]]


In [15]:

# Rule 3: If a dimension has size greater than 1 and both sizes are different, an error is raised.
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
b = np.array([[10, 20], [30, 40]])  # Shape: (2, 2)

# Broadcasting arrays with incompatible shapes (raises an error)
result = a + b